package export

import (
	"bytes"
	"fmt"
	"strings"
	"text/template"

	"github.com/grokify/pidl"
)

// PrefectExporter exports PIDL process specs to Prefect workflow Python code.
type PrefectExporter struct {
	// FlowName overrides the generated flow name.
	FlowName string
	// IncludeTasks generates task stubs.
	IncludeTasks bool
	// UseAsync generates async flow/tasks.
	UseAsync bool
}

// NewPrefectExporter creates a new Prefect exporter with defaults.
func NewPrefectExporter() *PrefectExporter {
	return &PrefectExporter{
		IncludeTasks: true,
		UseAsync:     true,
	}
}

// PrefectFlow represents a generated Prefect flow.
type PrefectFlow struct {
	FlowName       string
	FlowID         string
	Description    string
	Tasks          []PrefectTask
	ParallelBlocks []PrefectParallelBlock
	UseAsync       bool
}

// PrefectTask represents a Prefect task.
type PrefectTask struct {
	Name        string
	FuncName    string
	Description string
	Retries     int
	RetryDelay  string
	Timeout     string
	Tags        []string
	StepType    string
}

// PrefectParallelBlock represents a parallel execution block.
type PrefectParallelBlock struct {
	ID       string
	Tasks    []string
	JoinMode string
}

// Export converts a PIDL protocol to Prefect workflow Python code.
func (e *PrefectExporter) Export(p *pidl.Protocol) (string, error) {
	if p.ProtocolMeta.Kind != pidl.ProtocolKindProcess {
		return "", fmt.Errorf("prefect export only supports process specifications")
	}

	flow := e.buildFlow(p)
	return e.renderTemplate(flow)
}

func (e *PrefectExporter) buildFlow(p *pidl.Protocol) *PrefectFlow {
	flowName := e.FlowName
	if flowName == "" {
		flowName = toPythonName(p.ProtocolMeta.Name) + "_flow"
	}

	flow := &PrefectFlow{
		FlowName:    flowName,
		FlowID:      p.ProtocolMeta.ID,
		Description: p.ProtocolMeta.Description,
		Tasks:       []PrefectTask{},
		UseAsync:    e.UseAsync,
	}

	// Convert entities to tasks
	for _, entity := range p.Entities {
		if entity.StepType == "" {
			continue
		}

		task := PrefectTask{
			Name:        entity.Name,
			FuncName:    toPythonName(entity.Name) + "_task",
			Description: entity.Description,
			Tags:        []string{string(entity.StepType)},
			StepType:    string(entity.StepType),
		}

		// Set retries from entity config
		if entity.RetryStrategy != nil {
			task.Retries = entity.RetryStrategy.MaxAttempts
			task.RetryDelay = entity.RetryStrategy.InitialDelay
		}

		if entity.Processing != nil {
			task.Timeout = entity.Processing.Timeout
		}

		flow.Tasks = append(flow.Tasks, task)
	}

	// Detect parallel blocks
	blocks := pidl.DetectParallelBlocks(p)
	for _, block := range blocks {
		var tasks []string
		for _, branch := range block.Branches {
			tasks = append(tasks, toPythonName(branch.EntityID)+"_task")
		}

		flow.ParallelBlocks = append(flow.ParallelBlocks, PrefectParallelBlock{
			ID:       block.ID,
			Tasks:    tasks,
			JoinMode: string(block.JoinCondition),
		})
	}

	return flow
}

func (e *PrefectExporter) renderTemplate(flow *PrefectFlow) (string, error) {
	tmpl := `"""
{{.FlowName}} - Generated by PIDL
Source: {{.FlowID}}
{{- if .Description}}

{{.Description}}
{{- end}}
"""

from prefect import flow, task
{{- if .UseAsync}}
import asyncio
{{- end}}
from typing import Any, Dict
{{range .Tasks}}
@task(
    name="{{.Name}}",
{{- if .Retries}}
    retries={{.Retries}},
{{- end}}
{{- if .RetryDelay}}
    retry_delay_seconds={{.RetryDelay}},
{{- end}}
{{- if .Tags}}
    tags={{.Tags | pythonList}},
{{- end}}
)
{{- if $.UseAsync}}
async def {{.FuncName}}(data: Dict[str, Any]) -> Dict[str, Any]:
{{- else}}
def {{.FuncName}}(data: Dict[str, Any]) -> Dict[str, Any]:
{{- end}}
    """
    {{.Description}}

    Step Type: {{.StepType}}
    """
{{- if eq .StepType "deterministic"}}
    # Deterministic processing: same input always produces same output
    # Implement your deterministic transformation logic here
    result = data  # Replace with: transform_data(data)
    return result
{{- else if eq .StepType "llm"}}
    # LLM processing: non-deterministic AI/ML inference
    # Example with OpenAI:
    # import openai
    # client = openai.OpenAI()
    # response = client.chat.completions.create(
    #     model="gpt-4",
    #     messages=[{"role": "user", "content": str(data)}]
    # )
    # return {"result": response.choices[0].message.content, **data}
    return data
{{- else if eq .StepType "human"}}
    # Human-in-the-loop: requires human review or approval
    # Use Prefect artifacts or pause/resume for human input
{{- if $.UseAsync}}
    # Example:
    # from prefect import pause_flow_run
    # from prefect.artifacts import create_markdown_artifact
    # result = await create_markdown_artifact(f"## Review Required\n{data}")
    # approved = await pause_flow_run(wait_for_input=True)
{{- else}}
    # Example:
    # from prefect import pause_flow_run
    # approved = pause_flow_run(wait_for_input=True)
{{- end}}
    # if not approved:
    #     raise ValueError("Human approval denied")
    return data
{{- else if eq .StepType "external"}}
    # External service call: API or third-party integration
{{- if $.UseAsync}}
    # Example:
    # import httpx
    # async with httpx.AsyncClient() as client:
    #     response = await client.post(api_url, json=data)
    #     response.raise_for_status()
    #     return response.json()
{{- else}}
    # Example:
    # import requests
    # response = requests.post(api_url, json=data)
    # response.raise_for_status()
    # return response.json()
{{- end}}
    return data
{{- else if eq .StepType "tool"}}
    # Tool invocation: function or capability execution
{{- if $.UseAsync}}
    # result = await execute_tool(tool_name, data)
{{- else}}
    # result = execute_tool(tool_name, data)
{{- end}}
    # return result
    return data
{{- else}}
    # Generic processing step
    return data
{{- end}}
{{end}}

@flow(name="{{.FlowName}}")
{{- if .UseAsync}}
async def {{.FlowName}}(input_data: Dict[str, Any]) -> Dict[str, Any]:
{{- else}}
def {{.FlowName}}(input_data: Dict[str, Any]) -> Dict[str, Any]:
{{- end}}
    """
    {{.Description}}

    Generated from PIDL process specification: {{.FlowID}}
    """
    result = input_data
{{range .Tasks}}
{{- if $.UseAsync}}
    result = await {{.FuncName}}(result)
{{- else}}
    result = {{.FuncName}}(result)
{{- end}}
{{end}}
    return result
{{if .ParallelBlocks}}
# Parallel execution blocks
{{range .ParallelBlocks}}
# Block: {{.ID}} ({{.JoinMode}})
# Tasks: {{.Tasks | pythonList}}
{{end}}{{end}}

if __name__ == "__main__":
{{- if .UseAsync}}
    asyncio.run({{.FlowName}}({}))
{{- else}}
    {{.FlowName}}({})
{{- end}}
`

	funcMap := template.FuncMap{
		"pythonList": func(items []string) string {
			quoted := make([]string, len(items))
			for i, item := range items {
				quoted[i] = fmt.Sprintf(`"%s"`, item)
			}
			return "[" + strings.Join(quoted, ", ") + "]"
		},
	}

	t, err := template.New("prefect").Funcs(funcMap).Parse(tmpl)
	if err != nil {
		return "", fmt.Errorf("template parse error: %w", err)
	}

	var buf bytes.Buffer
	if err := t.Execute(&buf, flow); err != nil {
		return "", fmt.Errorf("template execute error: %w", err)
	}

	return buf.String(), nil
}

func toPythonName(s string) string {
	// Convert to Python-style snake_case
	s = strings.ReplaceAll(s, " ", "_")
	s = strings.ReplaceAll(s, "-", "_")
	return strings.ToLower(s)
}
