// Package export provides exporters for converting PIDL protocols to workflow engine formats.
package export

import (
	"bytes"
	"fmt"
	"strings"
	"text/template"

	"github.com/grokify/pidl"
)

// TemporalExporter exports PIDL process specs to Temporal workflow code.
type TemporalExporter struct {
	// PackageName is the Go package name for generated code.
	PackageName string
	// WorkflowName overrides the generated workflow name.
	WorkflowName string
	// IncludeActivities generates activity stubs.
	IncludeActivities bool
}

// NewTemporalExporter creates a new Temporal exporter with defaults.
func NewTemporalExporter() *TemporalExporter {
	return &TemporalExporter{
		PackageName:       "workflow",
		IncludeActivities: true,
	}
}

// TemporalWorkflow represents a generated Temporal workflow.
type TemporalWorkflow struct {
	PackageName    string
	WorkflowName   string
	WorkflowID     string
	Description    string
	Activities     []TemporalActivity
	Steps          []TemporalStep
	ParallelBlocks []TemporalParallelBlock
}

// TemporalActivity represents a workflow activity.
type TemporalActivity struct {
	Name        string
	Description string
	InputType   string
	OutputType  string
	Timeout     string
	Retries     int
}

// TemporalStep represents a step in the workflow.
type TemporalStep struct {
	Name            string
	ActivityName    string
	Description     string
	IsParallelStart bool
	IsParallelEnd   bool
	Condition       string
}

// TemporalParallelBlock represents a parallel execution block.
type TemporalParallelBlock struct {
	ID       string
	Branches []string
	JoinMode string
}

// Export converts a PIDL protocol to Temporal workflow Go code.
func (e *TemporalExporter) Export(p *pidl.Protocol) (string, error) {
	if p.ProtocolMeta.Kind != pidl.ProtocolKindProcess {
		return "", fmt.Errorf("temporal export only supports process specifications")
	}

	workflow := e.buildWorkflow(p)
	return e.renderTemplate(workflow)
}

func (e *TemporalExporter) buildWorkflow(p *pidl.Protocol) *TemporalWorkflow {
	workflowName := e.WorkflowName
	if workflowName == "" {
		workflowName = toGoName(p.ProtocolMeta.Name) + "Workflow"
	}

	workflow := &TemporalWorkflow{
		PackageName:  e.PackageName,
		WorkflowName: workflowName,
		WorkflowID:   p.ProtocolMeta.ID,
		Description:  p.ProtocolMeta.Description,
		Activities:   []TemporalActivity{},
		Steps:        []TemporalStep{},
	}

	// Convert entities to activities
	for _, entity := range p.Entities {
		if entity.StepType == "" {
			continue
		}

		activity := TemporalActivity{
			Name:        toGoName(entity.Name) + "Activity",
			Description: entity.Description,
			InputType:   "interface{}",
			OutputType:  "interface{}",
		}

		// Set timeout and retries from entity config
		if entity.Processing != nil {
			activity.Timeout = entity.Processing.Timeout
		}
		if entity.RetryStrategy != nil {
			activity.Retries = entity.RetryStrategy.MaxAttempts
		}

		workflow.Activities = append(workflow.Activities, activity)

		// Add step
		step := TemporalStep{
			Name:         entity.ID,
			ActivityName: activity.Name,
			Description:  entity.Description,
		}

		if entity.Parallel != nil {
			step.IsParallelStart = true
		}

		workflow.Steps = append(workflow.Steps, step)
	}

	// Detect parallel blocks
	blocks := pidl.DetectParallelBlocks(p)
	for _, block := range blocks {
		var branches []string
		for _, branch := range block.Branches {
			branches = append(branches, branch.EntityID)
		}

		workflow.ParallelBlocks = append(workflow.ParallelBlocks, TemporalParallelBlock{
			ID:       block.ID,
			Branches: branches,
			JoinMode: string(block.JoinCondition),
		})
	}

	return workflow
}

func (e *TemporalExporter) renderTemplate(workflow *TemporalWorkflow) (string, error) {
	tmpl := `// Code generated by PIDL. DO NOT EDIT.
// Source: {{.WorkflowID}}

package {{.PackageName}}

import (
	"context"
	"time"

	"go.temporal.io/sdk/activity"
	"go.temporal.io/sdk/workflow"
)

// {{.WorkflowName}} orchestrates the {{.WorkflowID}} process.
{{- if .Description}}
// {{.Description}}
{{- end}}
func {{.WorkflowName}}(ctx workflow.Context, input interface{}) (interface{}, error) {
	ao := workflow.ActivityOptions{
		StartToCloseTimeout: 10 * time.Minute,
		RetryPolicy: &temporal.RetryPolicy{
			MaximumAttempts: 3,
		},
	}
	ctx = workflow.WithActivityOptions(ctx, ao)

	var result interface{}
	var err error
{{range .Steps}}
	// Step: {{.Name}}
{{- if .Description}}
	// {{.Description}}
{{- end}}
{{- if .IsParallelStart}}
	// Parallel execution block
	selector := workflow.NewSelector(ctx)
{{- else}}
	err = workflow.ExecuteActivity(ctx, {{.ActivityName}}, input).Get(ctx, &result)
	if err != nil {
		return nil, err
	}
{{- end}}
{{end}}
	return result, nil
}
{{if .Activities}}
// Activities
{{range .Activities}}
// {{.Name}} - {{.Description}}
func {{.Name}}(ctx context.Context, input interface{}) (interface{}, error) {
	logger := activity.GetLogger(ctx)
	logger.Info("Executing {{.Name}}")

	// TODO: Implement activity logic
	return input, nil
}
{{end}}{{end}}`

	t, err := template.New("temporal").Parse(tmpl)
	if err != nil {
		return "", fmt.Errorf("template parse error: %w", err)
	}

	var buf bytes.Buffer
	if err := t.Execute(&buf, workflow); err != nil {
		return "", fmt.Errorf("template execute error: %w", err)
	}

	return buf.String(), nil
}

func toGoName(s string) string {
	// Convert to Go-style PascalCase
	words := strings.FieldsFunc(s, func(r rune) bool {
		return r == '_' || r == '-' || r == ' '
	})

	var result strings.Builder
	for _, word := range words {
		if len(word) > 0 {
			result.WriteString(strings.ToUpper(word[:1]))
			if len(word) > 1 {
				result.WriteString(strings.ToLower(word[1:]))
			}
		}
	}
	return result.String()
}
